[chain]
id = 42161000
name = "MyArbitrumChain"

[http]
addr = "0.0.0.0"
port = 8547
api = ["net", "web3", "eth", "debug", "arb"]

[execution.sequencer]
enable = true

[execution.sequencer.dangerous]
no-coordinator = true

[init]
preimagedir = "./preimages"

[parent-chain.connection]
url = "http://localhost:8545"
